[theme]
primaryColor="#00A9E0"            # Azul vibrante para widgets
backgroundColor="#FFFFFF"        # Fundo escuro padrão
secondaryBackgroundColor="#262730" # Fundo da sidebar um pouco mais claro
textColor="#0E1117"              # Texto branco/claro
font="sans serif"